# Generated by Django 5.2.14 on 2026-06-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='r2_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
