# Generated by Django 5.2.14 on 2026-06-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoupload_r2_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_upload_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.videoupload'),
        ),
    ]
