# Generated by Django 5.2.14 on 2026-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_user_emailuser_and_more'),
        ('videos', '0003_video_upload_onetoone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('video_id', 'user_id'), name='unique_review_per_user_video'),
        ),
    ]
