# Generated by Django 5.2.14 on 2026-06-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_user_emailuser_and_more'),
        ('videos', '0004_review_unique_per_user_video'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user_id', 'video_id'), name='unique_user_video_like'),
        ),
    ]
