# Generated by Django 5.2.14 on 2026-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
