# Generated by Django 5.2.14 on 2026-05-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
