# Generated by Django 5.2.14 on 2026-05-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_area_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_User',
            new_name='EmailUser',
        ),
        migrations.RenameModel(
            old_name='Social_User',
            new_name='SocialUser',
        ),
    ]
