# Generated by Codex on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_user_emailuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='housing_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
